package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func CreateCoderStarterFile(workspace string, opts AgentTemplateOptions) (string, error) {
	return createAgentFile(workspace, opts, renderCoderStarterTemplate(opts))
}

func CreateReviewerStarterFile(workspace string, opts AgentTemplateOptions) (string, error) {
	return createAgentFile(workspace, opts, renderReviewerStarterTemplate(opts))
}

func CreateReviewSynthStarterFile(workspace string, opts AgentTemplateOptions) (string, error) {
	return createAgentFile(workspace, opts, renderReviewSynthStarterTemplate(opts))
}

func CreateReviewflowCrewFile(workspace string, force bool) (string, error) {
	crewsDir := filepath.Join(workspace, "crews")
	if err := os.MkdirAll(crewsDir, 0o755); err != nil {
		return "", fmt.Errorf("create %s: %w", crewsDir, err)
	}
	outPath := filepath.Join(crewsDir, "reviewflow.yaml")
	if !force {
		if _, err := os.Stat(outPath); err == nil {
			return "", fmt.Errorf("%s already exists (use --force to overwrite)", outPath)
		}
	}
	if err := os.WriteFile(outPath, []byte(reviewflowCrewTemplate), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", outPath, err)
	}
	return outPath, nil
}

func renderCoderStarterTemplate(opts AgentTemplateOptions) string {
	model := strings.TrimSpace(opts.Model)
	if model == "" {
		model = "mock-small"
	}
	var b strings.Builder
	b.WriteString("name: coder\n")
	fmt.Fprintf(&b, "description: %s\n", yamlScalar("Starter code editing agent generated by deeph quickstart"))
	if p := strings.TrimSpace(opts.Provider); p != "" {
		fmt.Fprintf(&b, "provider: %s\n", p)
	} else {
		b.WriteString("# provider: your_provider_name  # optional if deeph.yaml has default_provider\n")
	}
	fmt.Fprintf(&b, "model: %s\n", model)
	b.WriteString("system_prompt: |\n")
	b.WriteString("  You are the coder agent for a deepH workspace.\n")
	b.WriteString("  Read only the files needed, keep edits focused, and avoid unnecessary churn.\n")
	b.WriteString("  Prefer line-range reads before writing.\n")
	b.WriteString("  When you change code, keep behavior coherent and summarize changed files plus residual risks.\n")
	b.WriteString("skills:\n")
	b.WriteString("  - file_read_range\n")
	b.WriteString("  - file_write_safe\n")
	b.WriteString("metadata:\n")
	b.WriteString("  tool_max_calls: \"6\"\n")
	b.WriteString("  max_tool_rounds: \"4\"\n")
	b.WriteString("  max_repeated_tool_calls: \"2\"\n")
	b.WriteString("  context_max_input_tokens: \"1200\"\n")
	b.WriteString("  context_moment: \"tool_loop\"\n")
	return b.String()
}

func renderReviewerStarterTemplate(opts AgentTemplateOptions) string {
	model := strings.TrimSpace(opts.Model)
	if model == "" {
		model = "mock-small"
	}
	var b strings.Builder
	b.WriteString("name: reviewer\n")
	fmt.Fprintf(&b, "description: %s\n", yamlScalar("Starter code review agent generated by deeph quickstart"))
	if p := strings.TrimSpace(opts.Provider); p != "" {
		fmt.Fprintf(&b, "provider: %s\n", p)
	} else {
		b.WriteString("# provider: your_provider_name  # optional if deeph.yaml has default_provider\n")
	}
	fmt.Fprintf(&b, "model: %s\n", model)
	b.WriteString("system_prompt: |\n")
	b.WriteString("  You are the reviewer agent for a deepH workspace.\n")
	b.WriteString("  Findings come first.\n")
	b.WriteString("  Prioritize bugs, regressions, missing tests, concurrency hazards, nil or pointer mistakes, API drift, resource leaks and risky assumptions.\n")
	b.WriteString("  Cite concrete file paths and explain impact.\n")
	b.WriteString("  If no convincing issue exists, say that explicitly and mention residual risks or testing gaps.\n")
	b.WriteString("skills:\n")
	b.WriteString("  - file_read_range\n")
	b.WriteString("metadata:\n")
	b.WriteString("  context_max_input_tokens: \"1400\"\n")
	b.WriteString("  context_max_recent_events: \"6\"\n")
	b.WriteString("  context_max_artifacts: \"4\"\n")
	b.WriteString("  context_max_facts: \"10\"\n")
	return b.String()
}

func renderReviewSynthStarterTemplate(opts AgentTemplateOptions) string {
	model := strings.TrimSpace(opts.Model)
	if model == "" {
		model = "mock-small"
	}
	var b strings.Builder
	b.WriteString("name: review_synth\n")
	fmt.Fprintf(&b, "description: %s\n", yamlScalar("Starter review synthesis agent generated by deeph quickstart"))
	if p := strings.TrimSpace(opts.Provider); p != "" {
		fmt.Fprintf(&b, "provider: %s\n", p)
	} else {
		b.WriteString("# provider: your_provider_name  # optional if deeph.yaml has default_provider\n")
	}
	fmt.Fprintf(&b, "model: %s\n", model)
	b.WriteString("system_prompt: |\n")
	b.WriteString("  You are the review_synth agent for a deepH workspace.\n")
	b.WriteString("  Reconcile upstream review findings from multiple universes.\n")
	b.WriteString("  Deduplicate overlaps, discard weak claims, rank remaining issues by severity and preserve file references.\n")
	b.WriteString("  If no convincing issue remains, say that explicitly and mention residual risks or testing gaps.\n")
	b.WriteString("metadata:\n")
	b.WriteString("  context_max_input_tokens: \"1400\"\n")
	b.WriteString("  context_max_recent_events: \"8\"\n")
	b.WriteString("  context_max_artifacts: \"6\"\n")
	b.WriteString("  context_max_facts: \"12\"\n")
	return b.String()
}

const reviewflowCrewTemplate = `name: reviewflow
description: Diff-aware review crew with focused universes and a final synth pass
spec: reviewer
universes:
  - name: baseline
    spec: reviewer
    output_kind: summary/text
    handoff_max_chars: 240

  - name: strict
    spec: reviewer
    output_kind: diagnostic/test
    handoff_max_chars: 240
    input_prefix: |
      [review_mode]
      mode: strict
      Focus on regressions, edge cases, missing tests, unsafe assumptions and overconfident conclusions.

  - name: go_focus
    spec: reviewer
    output_kind: diagnostic/build
    handoff_max_chars: 260
    input_prefix: |
      [review_mode]
      mode: go-specific
      Focus on Go semantics: context cancellation, goroutine leaks, channel misuse, nil and pointer handling, interface traps, error wrapping, sync hazards and io or resource cleanup.

  - name: tests_focus
    spec: reviewer
    output_kind: test/unit
    handoff_max_chars: 240
    input_prefix: |
      [review_mode]
      mode: tests
      Focus on missing tests, brittle assertions, integration gaps, fixture blind spots and why a bug could escape current coverage.

  - name: synth
    spec: review_synth
    output_kind: plan/summary
    depends_on: [baseline, strict, go_focus, tests_focus]
    merge_policy: append
    handoff_max_chars: 280
    input_prefix: |
      [review_mode]
      mode: synth
      Merge upstream review findings, deduplicate overlaps, rank severity, keep file references and say explicitly when no convincing bug was found.
`
